[package]
name = "bevy-gltf-component-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
# serde_with = "2.0"

bevy = "0.9"
bevy_rapier3d = "0.19"

